import "./globals.css";
import type { Metadata } from "next";
import Header from './header';
import { Inter } from "next/font/google";
import { PT_Serif } from "next/font/google";
import Link from 'next/link';

const PTSerif400 = PT_Serif({
  weight: "400",
  subsets: ["latin"],
  preload: false,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  // works,
}: {
  children: React.ReactNode;
  // works: React.ReactNode;
}) {
  return (
    <html lang="en" className={PTSerif400.className}>
      <body>
        <header className="text-gray-600 body-font bg-white">
          <div className="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
            <a className="flex title-font font-medium items-center text-black-1200 mb-4 md:mb-0">
              <span className="ml-3 text-xl">Portfolio</span>
            </a>
            {/* <nav className="md:ml-auto md:mr-auto flex flex-wrap items-center text-base justify-center"> */}
            <nav className="md:mr-auto md:ml-4 md:py-1 md:pl-4 md:border-l md:border-gray-400	flex flex-wrap items-center text-base justify-center">
              <Link className="mr-5 hover:text-gray-900" href="/">About</Link>
              <Link className="mr-5 hover:text-gray-900" href="/works">Works</Link>
            </nav>
          </div>
        </header>
        <div>{children}</div>
      </body>
    </html>
  );

}
